<?php $config = $this->getConfig(); ?>
<?php if (isset($config['group'])): ?>
    <?php
    $items = $this->getItems();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    ?>
    <nav class="navigation vicomage-megamenu " role="navigation">
        <ul id="mainMenu" class="nav nav-main">
            <?php echo $this->getCategorys(); ?>

            <?php if ($items) : ?>
                <?php foreach ($items as $item) {
                    echo $this->getMegamenuHtml($item);
                } ?>
            <?php endif; ?>
        </ul>
    </nav>
    <script type="text/javascript">
        require([
            'jquery',
            'megamenu'
        ], function ($) {
            $(".vicomage-megamenu").Megamenu();
        });
    </script>
<?php endif; ?>

