<?php
    $contacts_config = $this->helper('Vicomage\General\Helper\Data')->getConfig('vicomage_general_config/contacts');
    $_infoblock = $contacts_config['infoblock'];
?>
<div class="contact-content">
	<div class="row">
		<div class="col-sm-9"><?php echo $this->getChildHtml('contactForm')?></div>
		<div class="col-sm-3 contact-info">
			<div class="block-title">
				<strong><?php echo __('Contact Infomation') ?></strong>
			</div>
			<?php echo $_infoblock; ?>
		</div>
	</div>
</div>