<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$themeHelper = $this->helper('Vicomage\General\Helper\Data');

$_category_config = $this->helper('Vicomage\General\Helper\Data')->getConfig('vicomage_general_config/category');
$_category_grid_config = $this->helper('Vicomage\General\Helper\Data')->getConfig('vicomage_general_config/category_grid');
$_product_label_config = $this->helper('Vicomage\General\Helper\Data')->getConfig('vicomage_general_config/product_label');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
	
	<?php if ($block->getMode() == 'grid') { ?>
		<?php 
		$listCfg = array('mobile'=>$_category_grid_config['mobile'], 'portrait'=>$_category_grid_config['portrait'], 'landscape'=>$_category_grid_config['landscape'], 'tablet'=>$_category_grid_config['tablet'], 'notebook'=>$_category_grid_config['notebook'], 'visibleItems'=>$_category_grid_config['visible']);
		$devices = array(0 =>'mobile', 361 =>'mobile', 480 =>'portrait', 640=>'landscape', 768=>'tablet', 992=>'notebook', 1200=>'visibleItems');
		
		$prcents = array(1 => '100%', 2 => '50%', 3 => '33.333333333%', 4 => '25%', 5 => '20%', 6 => '16.666666666%');
		$styles = '';
		$padding = $_category_grid_config['category_item_padding'];
		$max = count($devices);
		$i   = $tmp= 1;
		foreach ($devices as $key => $value) {
			$tmpKey = ( $i == 1 || $i == $max) ? $value : current($devices);
			if($i >1){
				$styles .= ' @media (min-width: '. $tmp .'px) and (max-width: ' . ($key-1) . 'px) {.page-products .products-grid .product-item{ padding: 0 '.$padding.'px;width: '.$prcents[$listCfg[$value]] .'} .page-products .products-grid .product-item:nth-child(' .$listCfg[$value]. 'n+1){clear: left;}}';
				next($devices);           
			}
			if( $i == $max ) $styles .= ' @media (min-width: ' . $key . 'px) {.page-products .products-grid .product-item{ padding: 0 '.$padding.'px;width: '.$prcents[$listCfg[$value]] .'} .page-products .products-grid .product-item:nth-child(' .$listCfg[$value]. 'n+1){clear: left;}}';
			$tmp = $key;
			$i++;
		}
		?>
		<style type="text/css"><?php echo $styles ?></style>
	<?php } ?>
	
	
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
		 $hover_image = 'category_page_grid-hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
		 $hover_image = 'category_page_list-hover';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
	$image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:270;
    $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:320;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
					<?php
                    /* $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    } */
					
					
                    ?>
                    <?php // Product Image ?>
					<div class="product-img-hover">
						<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php
                            if($_category_config['aspect_ratio'])
                                $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                            else
                                $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                            $productImageUrl = $productImage->getUrl();
                        ?>
                            <img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                        <?php if($_category_config['alternative_image']): ?>
                        <?php
                            if($_category_config['aspect_ratio'])
                                $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                            else
                                $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);
                            $productHoverImageUrl = $productHoverImage->getUrl();
                        ?>
                            <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                            <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                            <?php endif; ?>
                        <?php endif; ?>
                        </a>
						<?php // Product Label ?>
						<?php echo $themeHelper->getProductLabel($_product) ?>
				</div>
                    <div class="product details product-item-details">
						<div class="product-details-wrapper">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
						<?php if($viewMode == 'grid' ): ?>
							<?php if($_category_config['product_price']): ?>
								<?php echo $block->getProductPrice($_product) ?>
							<?php endif; ?>
                        <?php endif; ?>
						
						
						
                        <?php echo $block->getProductDetailsHtml($_product); ?>
						<?php if ($showDescription):?>
							<div class="product description product-item-description">
								<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							</div>
						<?php endif; ?>
						<?php if($viewMode == 'grid' ): ?>
						<div class="product-item-inner">
							<?php if($_category_config['actions']): ?>
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary">
													<span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									
								</div>
							 <?php endif; ?>
							
                        </div>
						
						<?php endif; ?>
						</div>
						<?php if($viewMode == 'list' ): ?>
						<div class="product-info-list">
							<?php if ($_product->getIsSalable()): ?>
								<div class="stock available"><span class="label-stock"><?php /* @escapeNotVerified */ echo __('Avability:') ?></span><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
							<?php else: ?>
								<div class="stock unavailable"><span class="label-stock"><?php /* @escapeNotVerified */ echo __('Avability:') ?></span><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
							<?php endif; ?>
							<?php if($_category_config['product_price']): ?>
								<?php echo $block->getProductPrice($_product) ?>
							<?php endif; ?>
							<div class="product-item-inner">
								<?php if($_category_config['actions']): ?>
									<div class="product actions product-item-actions">
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="action tocart primary">
														<span><?php echo $block->escapeHtml(__('Add to Cart')); ?></span>
													</button>
												</form>
											<?php else: ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="action btn-details primary"><?php echo $block->escapeHtml(__('Detail')); ?></a>
											<?php endif; ?>
										</div>
										<?php if($_category_config['addtowishlist'] || $_category_config['addtocompare']): ?>
										
										<?php endif; ?>
									</div>
								<?php endif; ?>
							</div>
                        </div>
						<?php endif; ?>
					</div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
