<?php

if (!$this->_getConfig('is_enabled', 1)) {
    return;
}

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Vicomage\SearchBox\Helper\Data */
/** @var $helperSearch \Magento\Search\Helper\Data */

$helperSearch = $this->helper('Magento\Search\Helper\Data');
$helper = $this->helper('Vicomage\SearchBox\Helper\Data');
$tag_id = 'vico_searchbox' . rand() . time();
$cat_list = $this->getCategories();

$show_popular = $this->_getConfig('show_popular');
$limit_popular = $this->_getConfig('limit_popular');

$show_advanced = $this->_getConfig('show_advanced');

?>
<div id="<?php echo $tag_id; ?>" class="vico-searchbox">
    <?php
    if ($show_popular) { ?>
        <div class="vico-searchbox-popular">
            <div class="vico-searchbox-popular-title"><?php echo __('Top Search:'); ?></div>
            <div class="vico-searchbox-keyword">
                <?php require('searchbox.form.mini.ajax.phtml'); ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($show_advanced) { ?>
        <div class="vico-searchbox-advanced">
            <a href="<?php echo $this->getSearchBoxAdvanced(); ?>"><?php echo __('Advanced ++'); ?></a>
        </div>
    <?php } ?>

</div>

<script type="text/javascript">
    require(["jquery", "mage/template"], function () {
        //<![CDATA[
        jQuery(document).ready(function ($) {
            var searchbox = $('#<?php echo $tag_id;?>');
            var firt_load = <?php echo $limit_popular;?>;

            clickMore($('.vico-searchbox-more', searchbox));
            function clickMore(more) {
                more.click(function () {
                    var that = $(this);
                    var sb_ajaxurl = that.attr('data-ajaxmore');
                    var count = that.attr('data-count');
                    count = parseInt(count);
                    if (firt_load >= count) {
                        count = count + parseInt(firt_load);
                    }
                    $.ajax({
                        type: 'POST',
                        url: sb_ajaxurl,
                        data: {
                            is_ajax: 1,
                            count_term: count
                        },
                        success: function (data) {
                            $('.vico-searchbox-keyword', searchbox).html(data.htm);
                            clickMore($('a.vico-searchbox-more', searchbox));
                            $('a.vico-searchbox-more', searchbox).attr({
                                'data-count': count + parseInt(firt_load)
                            });
                        },
                        dataType: 'json'
                    });
                });
            }
        });
        //]]>
    });
</script>