<?php /* <div class="ajax-cart-container" id="ajax-cart-container" data-block='ajaxcartform' data-bind="scope: 'ajaxcart_content'" style="display:none;">
	<!-- ko template: getTemplate() --><!-- /ko -->
</div> */ ?>
<div class="cart-footer" id="cart-footer" data-bind="scope: 'ajaxcart_content'"  data-block="ajax_minicart">

</div>
<script type="text/x-magento-init">
{
	"[data-block='ajax_minicart']": {
		"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
	},
	"*": {
		"Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
	}
}
</script>